### PR TITLE
Fix: Make ChildrenAggregate as a SingleBucketAggregate

### LINKED ISSUE #305: [BUG] Deserializing ChildrenAggregate is broken
### What is the bug?
Deserializing ChildrenAggregate in the SearchResponse is broken.

The following error is being thrown.
```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'ChildrenAggregate.buckets'
```
### How can one reproduce the bug?
Write a ChildAggregation in the SearchRequest
```
 Aggregation aggregation = Aggregation.of(b -> b
                .children(cb -> cb
                        .type("child")
                )
);
SearchResponse<Doc> searchResponse = client.search(b -> b
                        .index(Index)
                        .query(query)
                        .aggregations("aggs", aggregation)
                , Doc.class
);
```

The following error is being thrown
```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'ChildrenAggregate.buckets'

	at org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:88)
	at org.opensearch.client.opensearch._types.aggregations.MultiBucketAggregateBase.<init>(MultiBucketAggregateBase.java:64)
	at org.opensearch.client.opensearch._types.aggregations.ChildrenAggregate.<init>(ChildrenAggregate.java:54)
	at org.opensearch.client.opensearch._types.aggregations.ChildrenAggregate.<init>(ChildrenAggregate.java:50)
	at org.opensearch.client.opensearch._types.aggregations.ChildrenAggregate$Builder.build(ChildrenAggregate.java:94)
	at org.opensearch.client.opensearch._types.aggregations.ChildrenAggregate$Builder.build(ChildrenAggregate.java:76)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:93)
	at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56)
	at org.opensearch.client.json.ExternallyTaggedUnion$Deserializer.deserialize(ExternallyTaggedUnion.java:77)
	at org.opensearch.client.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserializeEntry(ExternallyTaggedUnion.java:118)
	at org.opensearch.client.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserialize(ExternallyTaggedUnion.java:101)
	at org.opensearch.client.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserialize(ExternallyTaggedUnion.java:89)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88)
	at org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:85)
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:189)
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:150)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92)
	at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56)
	at org.opensearch.client.transport.endpoints.EndpointWithResponseMapperAttr$1.deserialize(EndpointWithResponseMapperAttr.java:69)
	at org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:320)
	at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:286)
	at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:143)
	at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1219)
	at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1234)

```
### What is the expected behavior?
Children Aggregation is single bucket aggregation, so I am not expecting multiple buckets

### What is your host/environment?
version
```
opensearch server 2.3.0
opensearch-java 1.0.0
opensearch-rest-client 1.3.2
```

Am I missing something?

### PR DESCRIPTION
**Pull request by sivaGH3**
Signed-off-by: Siva <ychnagasivareddy@gmail.com>

### Description
Make ChildrenAggregate as a SingleBucketAggregate.
Delete `ChildrenAggregateBucket.java`.
Tested the change.

### Issues Resolved
Closes #305 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by wbeckler — APPROVED** [review]

**Review by wbeckler — APPROVED** [review]

**Comment by wbeckler** [comment]
It might be helpful to add a test case for this.

**Comment by reta** [comment]
> It might be helpful to add a test case for this.

Certainly +1, we need a test case to show off the issue (and the fix in action)

**Comment by sivaGH3** [comment]
added ChildAggregation test case

**Comment by reta** [comment]
@sivaGH3 please fix checkstyle violations, thank you

**Review by reta — APPROVED** [review]

**Comment by siva-unravel** [comment]
@wbeckler please review this PR again, thanks

**Comment by wbeckler** [comment]
I'll defer to one of the maintainers to do the second review.

**Comment by siva-unravel** [comment]
@Bukhtawar @dblock @madhusudhankonda @saratvemulapalli @VachaShah , can I get one more review, thanks

**Review by saratvemulapalli — APPROVED** [review]
Thanks @sivaGH3 !!

**Comment by reta** [comment]
@sivaGH3 could you please backport to `2.x` as well? Thank you.

**Pull request merged**
