### PR TITLE
Update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by VijayanB**
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>

### Description
Add Madhusudhan Konda to maintainers list.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VijayanB** [comment]
@madhusudhankonda what shall i add for Affiliation?

**Comment by madhusudhankonda** [comment]
Chocolateminds will do?



Madhusudhan Konda


My Amazon's Page: Madhusudhan Konda<https://www.amazon.co.uk/Madhusudhan-Konda/e/B005IWJ740>

Author of All About Java 8 Lambdas<http://www.amazon.co.uk/All-About-Java-Lambdas-Introducing/dp/1517534585/>, Just Spring<https://www.amazon.co.uk/Just-Spring-Madhusudhan-Konda/dp/1449306403>, Just Hibernate<https://www.amazon.co.uk/Just-Hibernate-Madhusudhan-Konda/dp/1449334377>

Mobile: +44 7803712271

Tweet: @mkonda007

Home: www.madhusudhan.com<http://www.madhusudhan.com>

LinkedIn: linkedin.com/in/madhusudhankonda<https://www.linkedin.com/in/madhusudhankonda>



________________________________

**Comment by VijayanB** [comment]
@madhusudhankonda That works. Thanks.

**Review by madhusudhankonda — APPROVED** [review]
Coolio

**Pull request merged**
