### PR TITLE
Fixes deserialization of enums when using booleans instead of strings

### PR DESCRIPTION
**Pull request by patschl**
### Description
Allows for boolean values for enums which support those, eg. `DynamicMapping` and `Refresh`.

### Issues Resolved
Fixes https://github.com/opensearch-project/opensearch-java/issues/256

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by patschl** [comment]
I just tried it and actually no test fails, it's just an unexpected behaviour to implicitly support boolean deserialization with the Enum Deserializer.

If you'd like to I could move the new deserialization logic to the existing Deserializer.

**Comment by dblock** [comment]
> I just tried it and actually no test fails, it's just an unexpected behaviour to implicitly support boolean deserialization with the Enum Deserializer.
> 
> If you'd like to I could move the new deserialization logic to the existing Deserializer.

Yes yes!

**Comment by dblock** [comment]
Also please update documentation/README.

**Review by dblock — APPROVED** [review]
LGTM! No need to change anything in README.

**Review by reta — APPROVED** [review]

**Pull request merged**
