### PR TITLE
Fix integrationTest builds for JDK-11 sourcesets

### PR DESCRIPTION
**Pull request by reta**
### Description
Fix ntegrationTest builds for JDK-11 sourcesets

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Review by dblock — CHANGES_REQUESTED** [review]
https://github.com/opensearch-project/opensearch-java/actions/runs/8971819529?pr=968 (2.11) fails. The version check bash-style is a bit fragile :)

**Comment by reta** [comment]
> https://github.com/opensearch-project/opensearch-java/actions/runs/8971819529?pr=968 (2.11) fails. The version check bash-style is a bit fragile :)

Ah, the change came out in 2.12.0, fixing it, thanks @dblock !

**Review by VachaShah — APPROVED** [review]
Thank you @reta!

**Comment by reta** [comment]
@dblock LGTY?

**Review by dblock — APPROVED** [review]
LGTM.

**Pull request merged**
