### PR TITLE
Accept null values in arrays

### PR DESCRIPTION
**Pull request by sag1naev**
### Issues Resolved
Fixes: https://github.com/elastic/elasticsearch-java/issues/66

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
Thanks! Please add a test, sign with `git commit -s`, and confirm that this was implemented without looking at any non-APLv2 code.

**Comment by VachaShah** [comment]
@sag1naev Please let us know if you are facing issues with fixing DCO and if we can help :)

**Comment by wbeckler** [comment]
@sag1naev we'd love to get this in. Are you planning on trying to sort DCO for this?

**Comment by wbeckler** [comment]
@sag1naev, if you want this merged, please say so. I propose if this sits much longer we close without merging.

**Comment by VachaShah** [comment]
Closing this PR for now. @sag1naev Please feel free to reopen this PR or create a new one!

**Pull request closed without merging**
