### PR TITLE
Remove redundant SHA stage.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

I believe this is redundant since https://github.com/opensearch-project/opensearch-java/commit/f10608a1ec0b2cad5af2d3a99c475452cfffbf37 which has 

```
tasks.withType<Jar> {
    doLast {
        ant.withGroovyBuilder {
            "checksum"("algorithm" to "md5", "file" to archivePath)
            "checksum"("algorithm" to "sha1", "file" to archivePath)
            "checksum"("algorithm" to "sha-256", "file" to archivePath, "fileext" to ".sha256")
            "checksum"("algorithm" to "sha-512", "file" to archivePath, "fileext" to ".sha512")
        }
    }
}
```

If I run `./gradlew publishtoMavenLocal` I do get:

```
$ ls -la java-client/build/libs/
total 41080
drwxr-xr-x  17 dblock  staff       544 Jul 20 13:08 .
drwxr-xr-x  11 dblock  staff       352 Jul 28 09:21 ..
-rw-r--r--   1 dblock  staff  11544128 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-javadoc.jar
-rw-r--r--   1 dblock  staff        33 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-javadoc.jar.md5
-rw-r--r--   1 dblock  staff        41 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-javadoc.jar.sha1
-rw-r--r--   1 dblock  staff        65 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-javadoc.jar.sha256
-rw-r--r--   1 dblock  staff       129 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-javadoc.jar.sha512
-rw-r--r--   1 dblock  staff   2941651 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-sources.jar
-rw-r--r--   1 dblock  staff        33 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-sources.jar.md5
-rw-r--r--   1 dblock  staff        41 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-sources.jar.sha1
-rw-r--r--   1 dblock  staff        65 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-sources.jar.sha256
-rw-r--r--   1 dblock  staff       129 Jul 28 09:21 java-client-2.1.0-SNAPSHOT-sources.jar.sha512
-rw-r--r--   1 dblock  staff   4964277 Jul 28 09:20 java-client-2.1.0-SNAPSHOT.jar
-rw-r--r--   1 dblock  staff        33 Jul 28 09:20 java-client-2.1.0-SNAPSHOT.jar.md5
-rw-r--r--   1 dblock  staff        41 Jul 28 09:20 java-client-2.1.0-SNAPSHOT.jar.sha1
-rw-r--r--   1 dblock  staff        65 Jul 28 09:20 java-client-2.1.0-SNAPSHOT.jar.sha256
-rw-r--r--   1 dblock  staff       129 Jul 28 09:20 java-client-2.1.0-SNAPSHOT.jar.sha512
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Hey @dblock, we are not publishing this we are publishing `opensearch-java` from maven local (run ./gradlew publishtoMavenLocal at the root) it does not generate checksums. 

So this block of code was doing that via bash.

```
~/.m2/repository/org/opensearch/client/opensearch-java/2.1.0-SNAPSHOT  ls -l
total 37408
-rw-r--r--  1 gaiksaya  staff      1299 Jul 27 13:15 maven-metadata-local.xml
-rw-r--r--  1 gaiksaya  staff  11225194 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT-javadoc.jar
-rw-r--r--  1 gaiksaya  staff   2941651 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT-sources.jar
-rw-r--r--  1 gaiksaya  staff   4964279 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT.jar
-rw-r--r--  1 gaiksaya  staff      7935 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT.module
-rw-r--r--  1 gaiksaya  staff      3539 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT.pom

**Comment by dblock** [comment]
Superseded with https://github.com/opensearch-project/opensearch-java/pull/187

**Comment by dblock** [comment]
> Hey @dblock, we are not publishing this we are publishing `opensearch-java` from maven local (run ./gradlew publishtoMavenLocal at the root) it does not generate checksums.
> 
> So this block of code was doing that via bash.
> 
> ```
> ~/.m2/repository/org/opensearch/client/opensearch-java/2.1.0-SNAPSHOT  ls -l
> total 37408
> -rw-r--r--  1 gaiksaya  staff      1299 Jul 27 13:15 maven-metadata-local.xml
> -rw-r--r--  1 gaiksaya  staff  11225194 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT-javadoc.jar
> -rw-r--r--  1 gaiksaya  staff   2941651 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT-sources.jar
> -rw-r--r--  1 gaiksaya  staff   4964279 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT.jar
> -rw-r--r--  1 gaiksaya  staff      7935 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT.module
> -rw-r--r--  1 gaiksaya  staff      3539 Jul 27 13:15 opensearch-java-2.1.0-SNAPSHOT.pom
> ```

We're abusing `publishToMavenLocal`, that takes a publishable set of artifacts, then actually publishes it to local maven (~/.m2). What we should be doing is using the input to that, which can be obtained with #187 and  `./gradlew --no-daemon publishPublishMavenPublicationToSnapshotRepoRepository` for -SNAPSHOT builds, and `VERSION=2.1.0 ./gradlew --no-daemon publishPublishMavenPublicationToLocalRepoRepository` for producing local output that can be signed and uploaded to staging .

```
ORG_GRADLE_PROJECT_snapshotsUsername=... ORG_GRADLE_PROJECT_snapshotsPassword=... ./gradlew publishPublishMavenPublicationToSnapshotRepoRepository
```

```
VERSION=2.1.0 ./gradlew --no-daemon publishPublishMavenPublicationToLocalRepoRepository

$ ls -la ./build/repository/org/opensearch/client/opensearch-java/2.1.0/
total 38136
drwxr-xr-x  27 dblock  staff       864 Jul 28 14:42 .
drwxr-xr-x   8 dblock  staff       256 Jul 28 14:42 ..
-rw-r--r--   1 dblock  staff  11518615 Jul 28 14:42 opensearch-java-2.1.0-javadoc.jar
-rw-r--r--   1 dblock  staff        32 Jul 28 14:42 opensearch-java-2.1.0-javadoc.jar.md5
-rw-r--r--   1 dblock  staff        40 Jul 28 14:42 opensearch-java-2.1.0-javadoc.jar.sha1
-rw-r--r--   1 dblock  staff        64 Jul 28 14:42 opensearch-java-2.1.0-javadoc.jar.sha256
-rw-r--r--   1 dblock  staff       128 Jul 28 14:42 opensearch-java-2.1.0-javadoc.jar.sha512
-rw-r--r--   1 dblock  staff   2941649 Jul 28 14:42 opensearch-java-2.1.0-sources.jar
-rw-r--r--   1 dblock  staff        32 Jul 28 14:42 opensearch-java-2.1.0-sources.jar.md5
-rw-r--r--   1 dblock  staff        40 Jul 28 14:42 opensearch-java-2.1.0-sources.jar.sha1
-rw-r--r--   1 dblock  staff        64 Jul 28 14:42 opensearch-java-2.1.0-sources.jar.sha256
-rw-r--r--   1 dblock  staff       128 Jul 28 14:42 opensearch-java-2.1.0-sources.jar.sha512
-rw-r--r--   1 dblock  staff   4964269 Jul 28 14:42 opensearch-java-2.1.0.jar
-rw-r--r--   1 dblock  staff        32 Jul 28 14:42 opensearch-java-2.1.0.jar.md5
-rw-r--r--   1 dblock  staff        40 Jul 28 14:42 opensearch-java-2.1.0.jar.sha1
-rw-r--r--   1 dblock  staff        64 Jul 28 14:42 opensearch-java-2.1.0.jar.sha256
-rw-r--r--   1 dblock  staff       128 Jul 28 14:42 opensearch-java-2.1.0.jar.sha512
-rw-r--r--   1 dblock  staff      7796 Jul 28 14:42 opensearch-java-2.1.0.module
-rw-r--r--   1 dblock  staff        32 Jul 28 14:42 opensearch-java-2.1.0.module.md5
-rw-r--r--   1 dblock  staff        40 Jul 28 14:42 opensearch-java-2.1.0.module.sha1
-rw-r--r--   1 dblock  staff        64 Jul 28 14:42 opensearch-java-2.1.0.module.sha256
-rw-r--r--   1 dblock  staff       128 Jul 28 14:42 opensearch-java-2.1.0.module.sha512
-rw-r--r--   1 dblock  staff      3530 Jul 28 14:42 opensearch-java-2.1.0.pom
-rw-r--r--   1 dblock  staff        32 Jul 28 14:42 opensearch-java-2.1.0.pom.md5
-rw-r--r--   1 dblock  staff        40 Jul 28 14:42 opensearch-java-2.1.0.pom.sha1
-rw-r--r--   1 dblock  staff        64 Jul 28 14:42 opensearch-java-2.1.0.pom.sha256
-rw-r--r--   1 dblock  staff       128 Jul 28 14:42 opensearch-java-2.1.0.pom.sha512
```

**Comment by gaiksaya** [comment]
Sounds good! Thanks for clearing this out.

**Pull request closed without merging**
