### PR TITLE
Bug 744

### PR DESCRIPTION
**Pull request by dblock**
### Description

This is https://github.com/opensearch-project/opensearch-java/pull/748 so we don't lose it.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
@fs-chris Is there more to this than what's here? Code LGTM.

**Comment by fs-chris** [comment]
> @fs-chris Is there more to this than what's here? Code LGTM.

That's all I did.

**Comment by dblock** [comment]
Thanks. Someone please make this PR onto main and a backport on 2.x.

**Comment by fs-chris** [comment]
Any chance to get this into 2.x shortly?
If not, I'll once more have to revert our project back to the old REST high-level client since we need the scripted-upsert option.

**Comment by dblock** [comment]
@fs-chris Can you please make this PR into main?

**Comment by fs-chris** [comment]
> @fs-chris Can you please make this PR into main?

I didn't know how to jump onto this PR.
Created https://github.com/opensearch-project/opensearch-java/pull/856

**Comment by VachaShah** [comment]
This is done via #856

**Pull request closed without merging**
