### PR TITLE
Remove "THIS CODE IS GENERATED" comments 1 of 12

### PR DESCRIPTION
**Pull request by AarjavP**
same as #235 but broken down into different commits / branches.

Please let me know how / when the changelog should be submitted. 

I am creating just this 1 PR right now, but I have pushed other branches to my fork here: https://github.com/AarjavP/opensearch-java/branches
Most have < 200 files, and the one with most files has 213. If this is ok I can go ahead and create rest of the PRs.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by VachaShah** [comment]
Hi @AarjavP, sure this looks good!

**Comment by VachaShah** [comment]
@AarjavP You will have to add [Changelog](https://github.com/opensearch-project/opensearch-java/blob/main/CONTRIBUTING.md#changelog) to all your PRs.

**Comment by dblock** [comment]
@VachaShah You sure you want 12 (!) PRs instead of one big one? What's the advantage? Let's just merge #235, I am A-OK on that.

**Comment by AarjavP** [comment]
How about I push the 11 other commits into this PR and update the change log here only. I will close other 11 open PRs.

This way we can also avoid merge conflicts and merge commits due to change log. For review you can select one commit at a time instead of all at once.

**Comment by VachaShah** [comment]
@AarjavP still looking to finish this?

**Comment by VachaShah** [comment]
Done via #598

**Pull request closed without merging**
