### PR TITLE
Downgrade client to build with Java 8

### LINKED ISSUE #156: [PROPOSAL] Restore support for Java 8
## What kind of business use case are you trying to solve? What are your requirements?

Many users still need Java 8 for their clients for maximum Java compatibility.

**What is the problem? What is preventing you from meeting the requirements?**

With the introduction of OpenSearch 2.0.0, the OpenSearch 2.0.0 build has updated to Java 11. This also includes the `opensearch-rest-client` and `opensearch-rest-high-level-client` clients.

Users of clients who wish to update their client version must now update to Java 11.

Additionally, the opensearch-java client relies on the `opensearch-rest-client`. Per opensearch-project/opensearch-clients#17, this is the client which is meant to have the most compatibility. 

Here is an example of updating Data Prepper (which currently supports Java 8):

```
> No matching variant of org.opensearch.client:opensearch-rest-high-level-client:2.0.0-rc1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
    - Variant 'apiElements' capability org.opensearch.client:opensearch-rest-high-level-client:2.0.0-rc1 declares a library, packaged as a jar, and its dependencies declared externally:
        - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
    - Variant 'runtimeElements' capability org.opensearch.client:opensearch-rest-high-level-client:2.0.0-rc1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
        - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
```

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

I propose that the OpenSearch Core's `opensearch-rest-client` and `opensearch-rest-high-level-client` projects be made to use Java 8. The Gradle build can setup the `sourceCompatibility` and `targetCompatibility` to ensure that it uses only Java 8 language features.

An alternative solution would be to remove the dependency that `opensearch-java` has on `opensearch-rest-client`.

**What are your assumptions or prerequisites?**

None.

**What are remaining open questions?**

Can Gradle toolchains or another mechanism help ensure that the client projects do not use any Java 11 APIs?

### PR DESCRIPTION
**Pull request by harshavamsi**
### Description
Coming from #156, this downgrades the target to Java 8. This has to go in after #326.

### Issues Resolved
Closes #156 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dlvenable** [comment]
> > Nice! Thanks @harshavamsi !
> > Ideally, this project should also include the Java 8 in the build/test Java version matrix.
> > https://github.com/opensearch-project/opensearch-java/blob/a924a74e02b2fc6d2d7991f3365ff97e95a20d6b/.github/workflows/build.yml#L8-L10
> > 
> > I think ideally all the tests would run on Java 8 and 11. But, some of the integration tests require Java 11 due to the OpenSearch test framework. Maybe the project could run the build and unit tests on Java 8/11. And then run only integration tests on Java 11.
> 
> @dlvenable we cannot do that now, the `opensearch-java` uses `test-framework` from core - this is still JDK-11, so we either drop this dependency (copy tons of stuff) or use JDK-11+ for compile / build / test

This is probably beyond the scope of this PR, but we may wish to split the integration tests (which use the `test-framework`) from unit tests.

**Comment by dblock** [comment]
If we can run *some* basic tests with JDK8 I'd be satisfied. We can then run the full suite with JDK11 and have more work items about increasing test coverage on JDK8 by moving frameworks. Hope you can finish this @harshavamsi!

**Comment by rgopidiaws** [comment]
can you please prioritize this? we are currently blocked on this as we have a service which is using JDK8 and we are not able to use this client in that service. Appreciate it if you can prioritize this.

**Comment by dblock** [comment]
@rgopidiaws This hasn't been touched for a while so I am afraid nobody is working on this right now. Want to give it a try?

**Comment by VachaShah** [comment]
Closing this PR since restoring support for Java 8 is done.

**Pull request closed without merging**
