### PR TITLE
Document version auto-increment and fix typos.

### PR DESCRIPTION
**Pull request by dblock**
### Description

Document version auto-increment and fix typos.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — DISMISSED** [review]

**Comment by dblock** [comment]
@reta @Xtansia  I think I am getting confused to what's supposed to happen in which order for the release.

1. If I am releasing a 2.10.5, which branch is that supposed to happen on?
2. If I am releasing a 2.11.0, which branch is that supposed to happen on?
3. How do the instruction change for CHANGELOG, where do you make the changes first?

**Comment by reta** [comment]
> @reta @Xtansia I think I am getting confused to what's supposed to happen in which order for the release.

I think the branch versioning was a bit messed up:
 - `main` should be 3.0
 - `2.x` should have technically be `2.10.5-SNAPSHOT` (but it was 2.11.0)

So the sequence we follow for releases is:
 - branch of next release out of `2.x` (for example `2.11.0`)
 - update CHANGELOG in `2.11.0` (we need the commit for release)
 - push release tag (v2.11.0)
 - forwardport to `2.x` and `main`

**Comment by dblock** [comment]
Ok, @reta take a look at the updated instructions, does this capture this process?

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
> Ok, @reta take a look at the updated instructions, does this capture this process?

It does (in my opinion), thanks @dblock !

**Comment by Xtansia** [comment]
I don't know about the Java client, it looks like it's been doing branches per patch version off of 2.x. Normally for OpenSearch and at least the Rust & .NET clients, the branching is (assuming `2.10.4` is latest released):
* `main`: next major i.e. `3.0.0-SNAPSHOT`
* `2.x`: next minor i.e. `2.11.0-SNAPSHOT`
* `2.10`: next patch i.e. `2.10.5-SNAPSHOT`

Then releasing a new patch is:
1. Commit changelog to `2.10`
2. Tag `v2.10.5` on `2.10`
3. Auto build & release `v2.10.5`
4. Auto-increments `2.10` to developing `2.10.6-SNAPSHOT`

Releasing a new minor:
1. Commit changelog to `2.x`
2. Tag `v2.11.0` on `2.x`
3. Auto build & release `v2.11.0`
4. Auto-increment `2.x` to developing `2.12.0-SNAPSHOT`
5. Auto-branch and increment `2.11` to developing `2.11.1-SNAPSHOT`

Releasing a new major:
1. Commit changelog to `main`
2. Tag `v3.0.0` on `main`
3. Auto build & release `v3.0.0`
4. Auto-increment `main` to developing `4.0.0-SNAPSHOT`
5. Auto-branch and increment `3.x` to developing `3.1.0-SNAPHOT`
6. Auto-branch and increment `3.0` to developing `3.0.1-SNAPSHOT`

.NETs Bump Version Workflow: https://github.com/opensearch-project/opensearch-net/blob/main/.github/workflows/bump-version.yml

**Comment by dblock** [comment]
@Xtansia I think yours is clearer, take a look at the update please?

**Review by Xtansia — COMMENTED** [review]
All looks good to me, just a couple minor things to fix

**Review by Xtansia — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Pull request merged**
