### PR TITLE
Add Support for Hybrid Query Type

### PR DESCRIPTION
**Pull request by vibrantvarun**
### Description
Adds support for hybrid query type for  [in hybrid search](https://opensearch.org/docs/latest/search-plugins/hybrid-search/)

### Issues Resolved
[525](https://github.com/opensearch-project/neural-search/issues/525)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by VachaShah — COMMENTED** [review]
Thanks @vibrantvarun for adding this! It would be great to have the [user guide](https://github.com/opensearch-project/opensearch-java/blob/main/guides/search.md) and [samples](https://github.com/opensearch-project/opensearch-java/tree/main/samples/src/main/java/org/opensearch/client/samples) for `hyrbid` query type which would benefit the users.

**Comment by vibrantvarun** [comment]
Thanks @VachaShah . I will start working to add user guide and samples.

**Review by VachaShah — COMMENTED** [review]
I missed mentioning that we would also need to add an integration test for this. https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/test/java11/org/opensearch/client/opensearch/integTest/AbstractSearchRequestIT.java

**Comment by reta** [comment]
Looks great, thank you @vibrantvarun !

**Review by reta — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]
This is great!

**Pull request merged**
