### PR TITLE
Migrating from checkstyle to spotless for formatting

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
Adding spotless support in this repo in place of checkstyle so that we can get features for checking and applying the formatting using spotless. The rules used here are from the OpenSearch repo. `spotlessJavaCheck` is now part of the build task making it easier for developers to format their changes.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
Sorry @VachaShah , it is impossible to review the PRs as large as those: what we did for security & core - migrate per packages, in in chunks of no more than 300 files, it adds up some work but at least is feasible to go through the changes.

**Comment by VachaShah** [comment]
> Sorry @VachaShah , it is impossible to review the PRs as large as those: what we did for security & core - migrate per packages, in chunks of pull requests of no more than 300 files, it adds up some work but at least is feasible to go through the changes.

Yeah I thought about this after opening the PR 🙈 Let me break this down in multiple PRs without breaking the builds.

**Comment by dblock** [comment]
I wouldn't mind one massive PR as long as it's clear that the whole change is a couple of files and a separate "ran ./gradlew spotless:apply" kind of thing and all tests pass.

**Comment by VachaShah** [comment]
Thank you @dblock! I started dividing this, first PR is #648 which includes support for spotless and enabling spotless for some modules. The subsequent PRs will enable for other folders.

**Pull request closed without merging**
