### PR TITLE
[BUG] /_nodes/stats throwing serialization error

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
 /_nodes/stats,  /_nodes/info throwing serialization error

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-java/issues/47

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@VachaShah do you know if we still generate the model classes for Java client? if yes, could you share the process please?

**Comment by VachaShah** [comment]
> @VachaShah do you know if we still generate the model classes for Java client? if yes, could you share the process please?

The model classes are no longer generated for the Java client.

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
@VachaShah could you please take a look? thanks!

**Review by VachaShah — APPROVED** [review]
LGTM, thank you @reta!

**Comment by VachaShah** [comment]
@reta Can we also backport this fix to the 2.x branch?

**Pull request merged**
