### PR TITLE
Add timeout and throttle to the jenkins workflows

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add timeout and throttle to the jenkins workflows

### Issues Resolved

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
I dont think it is caused by my change on the ci tho. is it?

**Comment by VachaShah** [comment]
Reran the CI, there was some issue getting a particular dependency from maven during that time.

**Review by VachaShah — APPROVED** [review]

**Comment by VachaShah** [comment]
@peterzhuamazon This will now need a line in the Changelog.

**Comment by peterzhuamazon** [comment]
Hi @VachaShah I have updated the PR now.

Thanks.

**Review by VachaShah — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Pull request merged**
