### PR TITLE
[Backport 2.x] Fix PutTemplateRequest deserialization (#723)

### PR DESCRIPTION
**Pull request by VachaShah**
* fix PutTemplateRequest deserialization

* update changelog

* fix changelog PR number

* update for pr review

* update unit test for pr

* apply spotless check

---------

### Description
Backport of #723 to 2.x

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@VachaShah we may need to drop `2.8.3`, wdyt?

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@VachaShah needs a DCO update

**Comment by VachaShah** [comment]
> @VachaShah needs a DCO update

Done!

**Comment by VachaShah** [comment]
> @VachaShah we may need to drop `2.8.3`, wdyt?

For sure! we could do a `2.8.3` with this change.

**Pull request merged**
