### PR TITLE
Update to Gradle 7 (#69)

### LINKED ISSUE #67: Update to Gradle 7
**Is your feature request related to a problem? Please describe.**
The OpenSearch Java Client is still built using Gradle 6.6.x whereas the Gradle release train has moved to 7.x already. The OpenSearch core is about to be switched to Gradle 7.3 (see please opensearch-project/OpenSearch#1609), it would make sense to switch the build to Gradle 7.3 as well.

**Describe the solution you'd like**
 Update Gradle to 7.3

**Describe alternatives you've considered (Optional)**
N/A

**Additional context**
See please opensearch-project/OpenSearch#1246 and opensearch-project/opensearch-plugins#107

### PR DESCRIPTION
**Pull request by VachaShah**
* Update to Gradle 7

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

* Update to Gradle 7.3.3

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

* Restored copyright header

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Adding #69 to `main` since we fixed the branching in this repo. This commit is currently in [former-main](https://github.com/opensearch-project/opensearch-java/commits/former-main) branch.

This also resolves removing jcenter dependencies.
 
### Issues Resolved
#67, #114 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
@reta One more please, thank you!

**Review by reta — APPROVED** [review]

**Comment by VachaShah** [comment]
@reta Would you be able to fix the DCO on these commits? Its trying to find your gmail address in the check.

**Comment by reta** [comment]
@VachaShah mind if I reopen this pull request (or if you let me push to your branch, I could fix it)?

**Comment by VachaShah** [comment]
> @VachaShah mind if I reopen this pull request (or if you let me push to your branch, I could fix it)?

Yes ofcourse, I will close this PR. Thank you!

**Pull request closed without merging**
