### PR TITLE
Add workflow to publish snapshots via GHA

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Add workflow to publish snapshots via GHA.
Picked up the mentioned gradle task from here:
```
Publishing tasks
----------------
java-client:generateMetadataFileForPublishMavenPublication - Generates the Gradle metadata file for publication 'publishMaven'.
java-client:generatePomFileForPublishMavenPublication - Generates the Maven POM file for publication 'publishMaven'.
java-client:publish - Publishes all publications produced by this project.
java-client:publishAllPublicationsToLocalRepoRepository - Publishes all Maven publications produced by this project to the localRepo repository.
java-client:publishAllPublicationsToSnapshotsRepository - Publishes all Maven publications produced by this project to the Snapshots repository.
java-client:publishPublishMavenPublicationToLocalRepoRepository - Publishes Maven publication 'publishMaven' to Maven repository 'localRepo'.
java-client:publishPublishMavenPublicationToMavenLocal - Publishes Maven publication 'publishMaven' to the local Maven repository.
java-client:publishPublishMavenPublicationToSnapshotsRepository - Publishes Maven publication 'publishMaven' to Maven repository 'Snapshots'.
java-client:publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache
```

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — DISMISSED** [review]

**Comment by dblock** [comment]
Let's add some text to README or RELEASING linking to this workflow?

**Comment by gaiksaya** [comment]
> Let's add some text to README or RELEASING linking to this workflow?

Done! Please review. Thanks!

**Comment by gaiksaya** [comment]
FYI, I'll remove or disable this workflow since it won't be used anymore. https://build.ci.opensearch.org/job/opensearch-java-publish-snapshot/
Thanks!

**Review by VachaShah — APPROVED** [review]
Thank you @gaiksaya!

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Merged, remove the Jenkins one at will @gaiksaya

**Pull request merged**
