### PR TITLE
[Backport] [1.x] Fix: Make ChildrenAggregate as a SingleBucketAggregate (#306)

### PR DESCRIPTION
**Pull request by sivaGH3**
Signed-off-by: Siva <ychnagasivareddy@gmail.com>

### Description
Backport of #306 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
@sivaGH3 we usually dont release for existing released versions as we follow semver[1]. Can you consume latest 1.x ?
@wbeckler do we do anything different with clients?

[1] https://opensearch.org/releases.html#maintenance-policy

**Comment by sivaGH3** [comment]
@saratvemulapalli , how to consume latest 1.x, what are the steps? thanks!

**Comment by dblock** [comment]
I think you'll have to build and consume a private jar for anything that's no longer supported, https://stackoverflow.com/questions/4955635/how-to-add-local-jar-files-to-a-maven-project. Does this work?

**Comment by siva-unravel** [comment]
thanks! @dblock

**Pull request merged**
