### PR TITLE
Restore support for Java 8

### PR DESCRIPTION
**Pull request by reta**
### Description
Restore support for Java 8

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-java/issues/156

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
YES! Let's add CI.

**Comment by reta** [comment]
> YES! Let's add CI.

Thanks @dblock ! Working on it :)

**Comment by reta** [comment]
@dblock @VachaShah ended up with the following change:
 - the `opensearch-java` baseline is back to 1.8 (since RestClient is also back to 1.8)
 - the integration tests heavily rely on OpenSearch core test framework (it could not be switched to JDK 8), so this tests need JDK-11 baseline, the solution here (one of) is to split tests into `src/test/java` and `src/test/java11`
 - the Gradle build uses `grgit-gradle` 5.x that also needs JDK-11 baseline so we cannot build with JDK 8 sadly (it explains why GA/CI has no JDK 8 in matrix)

**Comment by dblock** [comment]
> * the Gradle build uses `grgit-gradle` 5.x that also needs JDK-11 baseline so we cannot build with JDK 8 sadly (it explains why GA/CI has no JDK 8 in matrix)

I think this should be a blocker. Can we downgrade? We need at least _some_ CI on JDK8, anything even a basic integration test would be enough.

**Review by dblock — DISMISSED** [review]
I would be ok we merge it with an issue on re-adding JDK8 to CI, unless it's doable with the downgrade of the dependent library.

**Comment by reta** [comment]
> I think this should be a blocker. Can we downgrade? We need at least _some_ CI on JDK8, anything even a basic integration test would be enough.

We could downgrade but to unsupported version (which is not good), alliteratively we could try to use other way to get the git details needed, I will look further

**Comment by dblock** [comment]
@VachaShah or @Bukhtawar ?

**Review by VachaShah — APPROVED** [review]
I am fine with merging this, thank you @reta for adding this! A few TODOs:
1. We can add the restored support details to the client documentation. For example, here https://github.com/opensearch-project/opensearch-java/blob/main/DEVELOPER_GUIDE.md.
2. As @dblock mentioned, CI with JDK-8.

**Comment by reta** [comment]
> As @dblock mentioned, CI with JDK-8.

Was trying to pull it off, but there are 3 blockers (previously I thought there is only 1 but it turns out Gradle reports issues one at a time):
 1. `grgit-gradle` - this one could be rewritten
 2. `spotless` - we need at least 6.23.x for JDK-21 but it seems like 6.11.x was the last one that supported JDK-8
 3. OpenSearch build tools (OpenSearch Gradle plugins) - needs JDK-11

So I am not sure what could we do here besides enforcing the target / source level

**Comment by reta** [comment]
> 1. . For example, here https://github.com/opensearch-project/opensearch-java/blob/main/DEVELOPER_GUIDE.md.

Thanks @VachaShah, we have this documented in the COMPATIBILITY.md, so updated the versions there

**Comment by dblock** [comment]
> So I am not sure what could we do here besides enforcing the target / source level

Open a GitHub issue?

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
> Open a GitHub issue?

For `grgit` and `spotless` decisions to move baselines to JDK-11 were deliberate (I could link the related issues if you are curious), so I don't think we should be opening an issue here. For OpenSearch build tools we probably could try to go with JDK 8 baseline but that would not solve the problem at large

**Review by VachaShah — APPROVED** [review]

**Comment by dblock** [comment]
Ok, I merged this, will need a manual backport - let's try to release a version that restored JDK8 support?

**Pull request merged**
