### PR TITLE
FIX: extract reason from error in AWSSdk2Transport

### PR DESCRIPTION
**Pull request by chenqi0805**
### Description
This is for resolving missing cause message when there is no proper permission to access Fine grained Access Control Amazon Opensearch domain.
```
Exception in thread "main" org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [security_exception] authentication/authorization failure
	at org.opensearch.client.transport.aws.AwsSdk2Transport.parseResponse(AwsSdk2Transport.java:517)
	at org.opensearch.client.transport.aws.AwsSdk2Transport.executeSync(AwsSdk2Transport.java:438)
	at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:241)
	at org.opensearch.client.opensearch.OpenSearchClient.bulk(OpenSearchClient.java:211)
	at org.opensearch.dataprepper.plugins.sink.opensearch.index.TestClient.testBulk(TestClient.java:215)
	at org.opensearch.dataprepper.plugins.sink.opensearch.index.TestClient.main(TestClient.java:80)
```

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-java/issues/473

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by wbeckler** [comment]
Thank you for submitting this! Can you think of a scenario in which an application might be relying on the previous behavior? As in, could this possibly be a breaking change?

**Comment by chenqi0805** [comment]
@wbeckler The only scenario I can think of is when both `reason` and `message` is present but so far it is hypothetical as I have not found such case. Do you have other scenario in your head?

**Comment by wbeckler** [comment]
> @wbeckler The only scenario I can think of is when both `reason` and `message` is present but so far it is hypothetical as I have not found such case. Do you have other scenario in your head?

Not really. What you're saying makes sense, but I ask the question in case there's something I'm not thinking of.

**Review by VachaShah — COMMENTED** [review]
LGTM! Just a minor comment.

**Review by VachaShah — APPROVED** [review]

**Review by dblock — CHANGES_REQUESTED** [review]
Looks good, but needs tests please.

**Comment by chenqi0805** [comment]
@dblock Thanks for the suggestion. I do not find a good strategy to unit test so I put a AwsSdk2SecurityIT that needs to be run against a FGAC without proper permission.

**Comment by dblock** [comment]
Without looking at the code, do we not have a way to mock a response? If it's really hard, care to open an issue to add tests that exercise all these paths and we'll merge as is? Also @reta wdyt?

**Comment by reta** [comment]
> Without looking at the code, do we not have a way to mock a response? If it's really hard, care to open an issue to add tests that exercise all these paths and we'll merge as is? Also @reta wdyt?

Sounds reasonable @dblock , we may need to come up with some mocks (like test fixtures we do in core) but it may take some efforts.

**Comment by wbeckler** [comment]
@chenqi0805 opened a separate issue for test coverage of transport: https://github.com/opensearch-project/opensearch-java/issues/503

**Comment by reta** [comment]
LGMT! @chenqi0805 there are conflicts, could you please resolve them? thank you

**Comment by chenqi0805** [comment]
@reta resolved conflict

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@dblock LGTY? thanks!

**Review by VachaShah — APPROVED** [review]

**Comment by chenqi0805** [comment]
@dblock Need your approval for unblocking merge

**Review by dblock — APPROVED** [review]

**Pull request merged**
