### PR TITLE
Revert support for JDK8.

### PR DESCRIPTION
**Pull request by dblock**
### Description

Supersedes https://github.com/opensearch-project/opensearch-java/pull/796 for 2.x.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock do you want me to revert the change and bundle everything into https://github.com/opensearch-project/opensearch-java/pull/798?

**Comment by dblock** [comment]
> @dblock do you want me to revert the change and bundle everything into #798?

I did the accidental merge so I feel guilty to create more work on you, let me do it.

Any reason not to merge this? I will take a variation of https://github.com/opensearch-project/opensearch-java/pull/798 next.

**Comment by reta** [comment]
> I did the accidental merge so I feel guilty to create more work on you, let me do it.

Don't worry about it, it will take me just a few mins

> Any reason not to merge this? I will take a variation of #798 next.

We need to bring tests from src/test/java11 back to src/test/java as well.

**Comment by dblock** [comment]
@reta Alright, thank you 🙏

**Pull request closed without merging**
