### PR TITLE
Fixes #1137 - Adding query_image to Neural query

### LINKED ISSUE #1137: [FEATURE] Add query_image to Neural query
### Is your feature request related to a problem?
Server side of Neural Query has an option to query_image which is not available in Java Client implementation.

### What solution would you like?
Add to NeuralQuery class imageQuery field and its corresponding serialization.

### What alternatives have you considered?
Create a local class, inherit and use it instead of the existing one. But its better to collaborate with the project.

### Do you have any additional context?
None.

### PR DESCRIPTION
**Pull request by urinud**
### Description
Fixes missing field for query_image in Neural Query. See [Neural query](https://opensearch.org/docs/latest/query-dsl/specialized/neural/).

### Issues Resolved
- Fixes #1137 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Thanks. If you can, please help make sure we don't break it via code generation. I see `query_image` in https://github.com/opensearch-project/opensearch-api-specification/blob/09824d0d0913a27ed9deeedf71fa4fffb1bed8ff/spec/schemas/_common.query_dsl.yaml#L1238, but I don't see any tests for it. Maybe you can add one into https://github.com/opensearch-project/opensearch-api-specification/tree/main/tests/default?

**Comment by urinud** [comment]
> Thanks. If you can, please help make sure we don't break it via code generation. I see `query_image` in https://github.com/opensearch-project/opensearch-api-specification/blob/09824d0d0913a27ed9deeedf71fa4fffb1bed8ff/spec/schemas/_common.query_dsl.yaml#L1238, but I don't see any tests for it. Maybe you can add one into https://github.com/opensearch-project/opensearch-api-specification/tree/main/tests/default?

@dblock , I manually added the changes into NeuralQuery in this project. That link that you send me is for another project. How are these projects related ?

**Comment by urinud** [comment]
Hello @Xtansia & @dblock , I reviewed the existing schema definition and executed the generator.
Before downloading the latest schema the generator executed, but not clases for querying where generated.
After downloading the latest version the generator thrown this error:
```
[CodeGenerator] FATAL - Unexpected Error
java.lang.IllegalArgumentException: Unknown status code: 204
        at org.opensearch.client.codegen.openapi.HttpStatusCode.from(HttpStatusCode.java:40) ~[main/:?]
        at org.opensearch.client.codegen.openapi.OpenApiElement.lambda$children$2(OpenApiElement.java:115) ~[main/:?]
        at org.opensearch.client.codegen.utils.Maps$EntryMapper.map(Maps.java:68) ~[main/:?]
```
I tried merging into the original file the Neural definition but then failed becase of the format binary not recognized:
```
[CodeGenerator] FATAL - Unexpected Error
java.lang.IllegalArgumentException: Unknown format: binary
        at org.opensearch.client.codegen.openapi.OpenApiSchemaFormat.from(OpenApiSchemaFormat.java:28) ~[main/:?]
        at org.opensearch.client.codegen.utils.Functional.ifNonnull(Functional.java:24) ~[main/:?]
        at org.opensearch.client.codegen.openapi.OpenApiSchema.<init>(OpenApiSchema.java:107) ~[main/:?]
        at org.opensearch.client.codegen.openapi.OpenApiElement.lambda$children$3(OpenApiElement.java:116) ~[main/:?]
        at org.opensearch.client.codegen.utils.Maps$EntryMapper.map(Maps.java:68) ~[main/:?]
```
Since the query_image is a String with a image in Base64 encoded format, seems safe to remove the format.
With that change the generation executed but still have not generated any query related object to check.
Thus I do not see compatibility issues with the schema definition and my change (except that I added a validation to check that at least one of the fields text or image are completed).
Not sure what else, I should check move forward.
Thank you

**Comment by urinud** [comment]
@dblock , I created this [PR](https://github.com/opensearch-project/opensearch-api-specification/pull/512) in the API specs project.
Hope I do now know how to create a test in that project. If you can give me detailed instructions I can try to help.
Regarding this change for the Java Client what else need to be done to move forward ?
Thank you

**Comment by urinud** [comment]
@Xtansia , are we good with this changes for this project ?
(I will keep working on the other)

**Review by Xtansia — APPROVED** [review]

**Pull request merged**
