### PR TITLE
Enabling spotless for all modules

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
Enabled spotless for all modules in the repo. Did it module by module per commit by running `./gradlew spotlessApply` for each.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
If you want to do a whole codebase like this at once, I don't mind merging a massive PR.

**Comment by VachaShah** [comment]
> If you want to do a whole codebase like this at once, I don't mind merging a massive PR.

Thank you @dblock! I will add all files for spotless changes in this PR divided by commits.

**Review by dblock — DISMISSED** [review]
Great! Who's fixing the link checker? :)

**Comment by VachaShah** [comment]
> Great! Who's fixing the link checker? :)

Haha, weird javadoc.io is not reachable since many days. Let me see if we can replace the link.

**Comment by VachaShah** [comment]
Found https://github.com/maxcellent/javadoc.io/issues/180.

**Comment by VachaShah** [comment]
@dblock I added the javadoc.io link in excludes in the latest commit till it is fixed.

I will create an issue to track this.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Let's merge this before it hits a conflict? @Bukhtawar @saratvemulapalli ?

**Review by saratvemulapalli — DISMISSED** [review]

**Comment by saratvemulapalli** [comment]
@VachaShah couple of conflicts :/

**Comment by VachaShah** [comment]
@dblock @saratvemulapalli Review again please? I fixed the merge conflicts and also removed the exclusion of the javadoc.io link since it is fixed now.

**Review by saratvemulapalli — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Do we backport this?

**Comment by VachaShah** [comment]
> Do we backport this?

Yeah I will backport this PR and the previous PR #648 manually to 2.x since there will be a lot of conflicts.

**Pull request merged**
